repos:

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: check-symlinks
      - id: check-added-large-files
        args: [--maxkb=500]
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-sort-keys]

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.48.0
    hooks:
      - id: markdownlint
        args:
          [
            "--config",
            ".markdownlint.json",
            "--ignore-path",
            ".markdownlintignore",
            "--fix",
          ]
        language: node
        # language_version: "14.17.6"
        pass_filenames: true
        types: [file, markdown, non-executable]

  - repo: local
    hooks:
      - id: prettier
        name: prettier
        language: node
        entry: prettier --write
        additional_dependencies:
          - prettier@3.5.3
        files: \.(css|scss|js)$

# Specific part for https://pre-commit.ci
ci:
  autofix_commit_msg: "[pre-commit.ci] Automatic fixes by pre-commit hooks."
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] Automatic updates of pre-commit hooks."
  autoupdate_schedule: monthly
  submodules: false
