name: "📦 Deploy to GitHub Pages"

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

  deploy:

    name: "📤 GitHub Pages"
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Inject Measurement ID
        env:
          GA_MEASUREMENT_ID: ${{ secrets.GA_MEASUREMENT_ID }}
        run: sed -i "s/__GA_MEASUREMENT_ID__/${GA_MEASUREMENT_ID}/g" docs/assets/javascript/consent.js

      - name: Zensical Action
        id: zensical
        uses: cssnr/zensical-action@v1
